CREATE OR REPLACE TRIGGER "CNL_SYS"."CNL_AS_RECONSILIATION_BIR_01" 
  BEFORE INSERT ON  CNL_SYS.CNL_AS_RECONSILIATION
 FOR EACH ROW
     WHEN (new.RECONSILE_KEY IS NULL) BEGIN
  :NEW.RECONSILE_KEY := CNL_AS_RECONSILIATION_SEQ1.NEXTVAL;
 END;