CREATE TABLE "CNL_SYS"."CNL_AS_ORDERS" 
   (	"FROM_SITE" VARCHAR2(20), 
	"CLIENT_ID" VARCHAR2(20), 
	"ORDER_ID" VARCHAR2(20), 
	"CREATION_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CUBED_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ORD_MASTER_HOST_MESSAGE_KEY" NUMBER, 
	"MANUAL_ORDER_STARTED" VARCHAR2(1), 
	"ORD_START_HOST_MESSAGE_KEY" NUMBER, 
	"CNL_IF_STATUS" VARCHAR2(50), 
	"ORD_TYPE" VARCHAR2(30), 
	"UPDATE_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_ORDERS_IDX" ON "CNL_SYS"."CNL_AS_ORDERS" ("CLIENT_ID", "ORDER_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_AS_ORDERS_STAT_IDX" ON "CNL_SYS"."CNL_AS_ORDERS" ("CNL_IF_STATUS") 
  ;