CREATE TABLE "CNL_SYS"."CNL_CTO_SHIP_LABELS" 
   (	"CLIENT_ID" VARCHAR2(30 CHAR), 
	"SITE_ID" VARCHAR2(30 CHAR), 
	"ORDER_ID" VARCHAR2(30 CHAR), 
	"SHIPMENT_ID" VARCHAR2(30 CHAR), 
	"PARCEL_ID" VARCHAR2(50 CHAR), 
	"PALLET_ID" VARCHAR2(50 CHAR), 
	"CONTAINER_ID" VARCHAR2(50 CHAR), 
	"PARCEL_HEIGHT" NUMBER, 
	"PARCEL_WIDTH" NUMBER, 
	"PARCEL_DEPTH" NUMBER, 
	"PARCEL_VOLUME" NUMBER, 
	"PARCEL_WEIGHT" NUMBER, 
	"RUN_TASK_KEY" NUMBER(*,0), 
	"PALLET_OR_CONTAINER" VARCHAR2(10 CHAR), 
	"PALLET_TYPE" VARCHAR2(50 CHAR), 
	"SHP_LABEL" CLOB, 
	"CARRIER_ID" VARCHAR2(30 CHAR), 
	"SERVICE_LEVEL" VARCHAR2(30 CHAR), 
	"TRACKING_NUMBER" VARCHAR2(50 CHAR), 
	"TRACKING_URL" VARCHAR2(200 CHAR), 
	"CTO_SSCC" VARCHAR2(50 CHAR), 
	"CREATION_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"STATUS" VARCHAR2(50 CHAR), 
	"UPDATE_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"PRINTER_NAME" VARCHAR2(200 CHAR), 
	"DWS" VARCHAR2(1 CHAR), 
	"COPIES" NUMBER, 
	"SHP_LABEL_BASE64" CLOB, 
	 CONSTRAINT "CNL_SHP_LABEL_PK" PRIMARY KEY ("CLIENT_ID", "SITE_ID", "PARCEL_ID", "RUN_TASK_KEY", "PRINTER_NAME")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_SHP_LABEL_IDX1" ON "CNL_SYS"."CNL_CTO_SHIP_LABELS" ("ORDER_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_SHP_LABEL_IDX2" ON "CNL_SYS"."CNL_CTO_SHIP_LABELS" ("SHIPMENT_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_SHP_LABEL_IDX3" ON "CNL_SYS"."CNL_CTO_SHIP_LABELS" ("TRACKING_NUMBER") 
  ;

CREATE INDEX "CNL_SYS"."CNL_SHP_LABEL_IDX4" ON "CNL_SYS"."CNL_CTO_SHIP_LABELS" ("PARCEL_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_SHP_LABEL_IDX5" ON "CNL_SYS"."CNL_CTO_SHIP_LABELS" ("STATUS") 
  ;