CREATE TABLE "CNL_SYS"."CNL_CTO_AUTHENTICATE_KEY" 
   (	"AUTHENTICATE_KEY" VARCHAR2(200 CHAR) DEFAULT 'NOKEY', 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ATTEMPT" NUMBER(*,0), 
	"CREATED_ON_DATABSE" VARCHAR2(20 CHAR)
   ) ;