CREATE TABLE "CNL_SYS"."CNL_CLIENT_VAS_ACTIVITY" 
   (	"ID" NUMBER, 
	"ACTIVITY_ID" NUMBER, 
	"VAS_CODE_ID" NUMBER, 
	"ACTIVITY_SEQUENCE" NUMBER NOT NULL ENABLE, 
	"CLIENT_ID" VARCHAR2(30 CHAR), 
	"CUSTOMER_ID" VARCHAR2(50 CHAR), 
	"COUNTRY" VARCHAR2(3 CHAR), 
	"SKU_ID" VARCHAR2(50 CHAR), 
	"ACTIVITY_INSTRUCTION" VARCHAR2(4000 CHAR), 
	 CONSTRAINT "PRIMARY_KEY" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "FK_ACTIVITY_ID" FOREIGN KEY ("ACTIVITY_ID")
	  REFERENCES "CNL_SYS"."CNL_VAS_ACTIVITY" ("ID") ENABLE, 
	 CONSTRAINT "FK_VAS_CODE_ID" FOREIGN KEY ("VAS_CODE_ID")
	  REFERENCES "CNL_SYS"."CNL_AS_VAS_CODES" ("ID") ENABLE
   ) ;