CREATE TABLE "CNL_SYS"."CNL_AS_ADJUSTMENT" 
   (	"ADJUSTMENT_KEY" NUMBER, 
	"SITE_ID" VARCHAR2(20), 
	"CLIENT_ID" VARCHAR2(30), 
	"SKU_ID" VARCHAR2(50), 
	"TAG_ID" VARCHAR2(50), 
	"QUANTITY" NUMBER, 
	"PREV_QUANTITY" NUMBER, 
	"ADJUSTED_QUANTITY" NUMBER, 
	"ADJUSTMENT_REASON" VARCHAR2(50), 
	"PROCESSED_QUANTITY" NUMBER, 
	"LOAD_UNIT_KEY" NUMBER, 
	"INVENTORY_STATUS_KEY" NUMBER, 
	"PROCESSED" VARCHAR2(1), 
	"PROCES_ERROR" VARCHAR2(1), 
	"CREATION_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_ADJUSTMENT_IDX" ON "CNL_SYS"."CNL_AS_ADJUSTMENT" ("ADJUSTMENT_KEY") 
  ;