CREATE TABLE "CNL_SYS"."CNL_CONTAINER_DATA" 
   (	"CONTAINER_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CONTAINER_TYPE" VARCHAR2(15 CHAR), 
	"PALLET_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"PALLET_TYPE" VARCHAR2(15 CHAR), 
	"CONTAINER_N_OF_N" NUMBER(3,0), 
	"SITE_ID" VARCHAR2(10 CHAR), 
	"CLIENT_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"OWNER_ID" VARCHAR2(10 CHAR), 
	"ORDER_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"CUSTOMER_ID" VARCHAR2(15 CHAR), 
	"CARRIER_ID" VARCHAR2(25 CHAR), 
	"SERVICE_LEVEL" VARCHAR2(40 CHAR), 
	"WMS_WEIGHT" NUMBER(15,6), 
	"WMS_HEIGHT" NUMBER(15,6), 
	"WMS_WIDTH" NUMBER(15,6), 
	"WMS_DEPTH" NUMBER(15,6), 
	"WMS_DATABASE" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DWS_UNIT_ID" VARCHAR2(20 CHAR), 
	"DWS_STATION_ID" VARCHAR2(256 CHAR), 
	"DWS_LFT_STATUS" VARCHAR2(20 CHAR), 
	"DWS_LFT_DESCRIPTION" VARCHAR2(500 CHAR), 
	"DWS_PACKAGE_TYPE" VARCHAR2(15 CHAR), 
	"DWS_WEIGHT" NUMBER(15,6), 
	"DWS_HEIGHT" NUMBER(15,6), 
	"DWS_WIDTH" NUMBER(15,6), 
	"DWS_DEPTH" NUMBER(15,6), 
	"DWS_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CTO_ENABLED_YN" VARCHAR2(1 CHAR) DEFAULT 'N' NOT NULL ENABLE, 
	"CTO_PP_FILENAME" VARCHAR2(100 CHAR), 
	"CTO_PP_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CTO_CP_FILENAME" VARCHAR2(100 CHAR), 
	"CTO_CP_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CTO_CARRIER" VARCHAR2(25 CHAR), 
	"CTO_SERVICE" VARCHAR2(40 CHAR), 
	"CTO_SEQUENCE_NR" VARCHAR2(50 CHAR), 
	"CTO_TRACKING_NR" VARCHAR2(50 CHAR), 
	"CTO_TRACKING_URL" VARCHAR2(1000 CHAR), 
	"CTO_ERROR_CODE" VARCHAR2(50 CHAR), 
	"CTO_ERROR_MESSAGE" VARCHAR2(1500 CHAR), 
	"CTO_PPR_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CREATED_BY" VARCHAR2(20 CHAR), 
	"CREATION_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(20 CHAR), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ARCHIVED" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"ARCHIVED_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ARCHIVE_PENDING" VARCHAR2(1 CHAR) DEFAULT 'N', 
	 CONSTRAINT "PK_CNL_CONTAINER_DATA" PRIMARY KEY ("WMS_DATABASE", "ORDER_ID", "CLIENT_ID", "CONTAINER_ID", "PALLET_ID")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."IDX_CDA_CLIENT" ON "CNL_SYS"."CNL_CONTAINER_DATA" ("CLIENT_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_CDA_CONTAINER_ID" ON "CNL_SYS"."CNL_CONTAINER_DATA" ("CONTAINER_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_CDA_ORDER_ID" ON "CNL_SYS"."CNL_CONTAINER_DATA" ("ORDER_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_CDA_PALLET_ID" ON "CNL_SYS"."CNL_CONTAINER_DATA" ("PALLET_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_CDA_WMS_DATABASE" ON "CNL_SYS"."CNL_CONTAINER_DATA" ("WMS_DATABASE") 
  ;