CREATE TABLE "CNL_SYS"."CNL_AS_MAAS_LOGGING" 
   (	"KEY" NUMBER, 
	"MHE_POSITION_NUMBER" VARCHAR2(20 CHAR), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CONTAINER_ID" VARCHAR2(50 CHAR), 
	"MHE_STATION_ID" VARCHAR2(256 CHAR), 
	"DWS_PACKAGE_TYPE" VARCHAR2(50 CHAR), 
	"DWS_BOX_WEIGHT" NUMBER, 
	"DWS_BOX_HEIGHT" NUMBER, 
	"DWS_BOX_WIDTH" NUMBER, 
	"DWS_BOX_DEPTH" NUMBER, 
	"SORT_PALLET_ID" VARCHAR2(50 CHAR), 
	"SORT_PALLET_TYPE" VARCHAR2(50 CHAR), 
	"PRINT_DOCUMENTS" VARCHAR2(1 CHAR), 
	"CLOSE_BOX" VARCHAR2(1 CHAR), 
	"BYPASS" VARCHAR2(1 CHAR), 
	"PRINT_LABEL" VARCHAR2(1 CHAR), 
	"SORTATION_LOC" VARCHAR2(30 CHAR), 
	"TRACKING_NUMBER" VARCHAR2(100 CHAR), 
	"INSTRUCTION" LONG, 
	"OK" VARCHAR2(1 CHAR), 
	"ERROR_MESSAGE" VARCHAR2(4000 CHAR), 
	"SKIP_VALIDATION" VARCHAR2(1 CHAR), 
	"MATCH_OR_CONTAINS" VARCHAR2(50 CHAR), 
	"ARCHIVED" VARCHAR2(1 CHAR) DEFAULT 'N', 
	"ARCHIVED_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ARCHIVE_PENDING" VARCHAR2(1 CHAR) DEFAULT 'N', 
	 UNIQUE ("KEY")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_MAAS_LOGGING_IDX" ON "CNL_SYS"."CNL_AS_MAAS_LOGGING" ("CONTAINER_ID", "KEY") 
  ;