CREATE TABLE "CNL_SYS"."CNL_CTO_LOG" 
   (	"LOG_KEY" NUMBER, 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"SOURCE" VARCHAR2(100 CHAR), 
	"DESCRIPTION" VARCHAR2(4000 CHAR)
   ) ;

CREATE INDEX "CNL_SYS"."CNL_CTO_LOG_IDX" ON "CNL_SYS"."CNL_CTO_LOG" ("LOG_KEY") 
  ;