CREATE TABLE "CNL_SYS"."CNL_ORDER_SEQUENCES" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLIENT_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"OSE_TYPE" VARCHAR2(3 CHAR) DEFAULT 'INV' NOT NULL ENABLE, 
	"UDP_1" VARCHAR2(10 CHAR), 
	"UDP_2" VARCHAR2(10 CHAR), 
	"PREFIX" VARCHAR2(5 CHAR), 
	"SUFFIX" VARCHAR2(5 CHAR), 
	"MIN_VALUE" NUMBER(10,0), 
	"MAX_VALUE" NUMBER(10,0), 
	"INCREMENT_BY" NUMBER(4,0) DEFAULT 1 NOT NULL ENABLE, 
	"ZERO_PAD" NUMBER(2,0) DEFAULT 0 NOT NULL ENABLE, 
	"LAST_USED" NUMBER(10,0) DEFAULT 0 NOT NULL ENABLE, 
	"START_DATE" DATE DEFAULT sysdate NOT NULL ENABLE, 
	"END_DATE" DATE, 
	"CREATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	"CONCURRENCY_KEY" VARCHAR2(32 CHAR) DEFAULT SYS_GUID() NOT NULL ENABLE, 
	"USED_IN" VARCHAR2(10 CHAR), 
	 CONSTRAINT "CNL_OSE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CNL_OSE_UK1" UNIQUE ("CLIENT_ID", "OSE_TYPE", "UDP_1", "UDP_2", "START_DATE", "END_DATE")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."IDX_OSE_CLIENT" ON "CNL_SYS"."CNL_ORDER_SEQUENCES" ("CLIENT_ID") 
  ;