CREATE TABLE "CNL_SYS"."CNL_AS_MANUAL_ORDER_STARTED" 
   (	"CLIENT_ID" VARCHAR2(50 CHAR), 
	"ORDER_ID" VARCHAR2(50 CHAR), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"PROCESSED" VARCHAR2(1 CHAR), 
	"CNL_IF_STATUS" VARCHAR2(50 CHAR)
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_MAN_ORDER_STARTED_IDX" ON "CNL_SYS"."CNL_AS_MANUAL_ORDER_STARTED" ("CLIENT_ID", "ORDER_ID") 
  ;