CREATE TABLE "CNL_SYS"."CNL_CTO_WEBSERVICE_BODY" 
   (	"KEY" NUMBER(*,0), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"REQUEST" CLOB, 
	"RESPONSE" CLOB, 
	"STATUS_CODE" VARCHAR2(30 CHAR), 
	"WEB_SERVICE_NAME" VARCHAR2(100 CHAR), 
	 CONSTRAINT "CNL_CTO_WEBSERVICE_BODY_PK" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_CTO_WEBSERVICE_BODY_IDX1" ON "CNL_SYS"."CNL_CTO_WEBSERVICE_BODY" ("DSTAMP") 
  ;