CREATE TABLE "CNL_SYS"."CNL_AS_VAS_CODES" 
   (	"ID" NUMBER(*,0), 
	"VAS_CODES" NUMBER, 
	"DESCRIPTION" VARCHAR2(100 CHAR), 
	 CONSTRAINT "UN_VAS_CODES" UNIQUE ("VAS_CODES")
  USING INDEX  ENABLE, 
	 CONSTRAINT "PK_VAS_CODES" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;