CREATE TABLE "CNL_SYS"."CNL_PRINT_LOG" 
   (	"LOG_KEY" NUMBER, 
	"PRINT_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(100 CHAR), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"SOURCE_PACKAGE" VARCHAR2(30 CHAR), 
	"SOURCE_ROUTINE" VARCHAR2(30 CHAR), 
	"ROUTINE_STEP" VARCHAR2(4000 CHAR), 
	"CODE_PARAMETERS" VARCHAR2(4000 CHAR), 
	"ORDER_ID" VARCHAR2(50 CHAR), 
	"CLIENT_ID" VARCHAR2(50 CHAR), 
	"PALLET_ID" VARCHAR2(50 CHAR), 
	"CONTAINER_ID" VARCHAR2(50 CHAR), 
	"SITE_ID" VARCHAR2(50 CHAR), 
	 CONSTRAINT "CNL_PRINT_LOG_PK" PRIMARY KEY ("LOG_KEY")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX1" ON "CNL_SYS"."CNL_PRINT_LOG" ("PRINT_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX2" ON "CNL_SYS"."CNL_PRINT_LOG" ("FILE_NAME") 
  ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX3" ON "CNL_SYS"."CNL_PRINT_LOG" ("DSTAMP") 
  ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX4" ON "CNL_SYS"."CNL_PRINT_LOG" ("ORDER_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX5" ON "CNL_SYS"."CNL_PRINT_LOG" ("CLIENT_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX6" ON "CNL_SYS"."CNL_PRINT_LOG" ("PALLET_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_PRINT_LOG_IDX7" ON "CNL_SYS"."CNL_PRINT_LOG" ("CONTAINER_ID") 
  ;