CREATE TABLE "CNL_SYS"."CNL_ACTIVE_CLIENTS" 
   (	"DB_LINK" VARCHAR2(7 CHAR), 
	"SITE_ID" VARCHAR2(10 CHAR), 
	"CLIENT_ID" VARCHAR2(10 CHAR), 
	 CONSTRAINT "PK_CNL_ACTIVE_CLIENTS" PRIMARY KEY ("DB_LINK", "SITE_ID", "CLIENT_ID")
  USING INDEX  ENABLE
   ) ;