CREATE TABLE "CNL_SYS"."CNL_AS_MANUAL_LINES" 
   (	"CLIENT_ID" VARCHAR2(50), 
	"ORDER_ID" VARCHAR2(50), 
	"LINE_ID" NUMBER(6,0), 
	"SKU_ID" VARCHAR2(50), 
	"MT_KEY" NUMBER(20,0), 
	"MT_QTY" NUMBER(20,0), 
	"QTY_PICKED" NUMBER(20,0), 
	"FINISHED" VARCHAR2(1) DEFAULT 'N', 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CATEGORY" VARCHAR2(50)
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_MAN_LINES_IDX" ON "CNL_SYS"."CNL_AS_MANUAL_LINES" ("CLIENT_ID", "ORDER_ID", "LINE_ID", "SKU_ID") 
  ;