CREATE TABLE "CNL_SYS"."CNL_AS_PICKED_ATTRIBUTES" 
   (	"ATTRIBUTE_TYPE" VARCHAR2(50), 
	"CLIENT_ID" VARCHAR2(50), 
	"ORDER_ID" VARCHAR2(50), 
	"WMS_LINE_ID" NUMBER, 
	"WMS_MT_KEY" NUMBER, 
	"SKU_ID" VARCHAR2(50), 
	"TAG_ID" VARCHAR2(50), 
	"SERIAL_NUMBER" VARCHAR2(4000), 
	"BATCH_ID" VARCHAR2(50), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"TU_ID" VARCHAR2(50)
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_PICKED_ATTRIBUTE_IDX" ON "CNL_SYS"."CNL_AS_PICKED_ATTRIBUTES" ("CLIENT_ID", "ORDER_ID", "SKU_ID", "TAG_ID") 
  ;