CREATE TABLE "CNL_SYS"."CNL_AS_PROCESSED_HOST_MESSAGE" 
   (	"KEY" NUMBER, 
	"MESSAGE_TYPE" VARCHAR2(100), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_PROC_HME_IDX" ON "CNL_SYS"."CNL_AS_PROCESSED_HOST_MESSAGE" ("KEY") 
  ;