CREATE TABLE "CNL_SYS"."CNL_AS_TU" 
   (	"WMS_CONTAINER_ID" VARCHAR2(30), 
	"WMS_ORDER_ID" VARCHAR2(30), 
	"WMS_CONTAINER_TYPE" VARCHAR2(30), 
	"WMS_CLIENT_ID" VARCHAR2(20), 
	"CNL_IF_STATUS" VARCHAR2(50), 
	"MAN_PICK_HOST_MESSAGE_KEY" NUMBER, 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CONTAINER_WEIGHT" NUMBER, 
	"LAST_BOX" NUMBER
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_TU_IDX" ON "CNL_SYS"."CNL_AS_TU" ("WMS_CONTAINER_ID", "WMS_ORDER_ID", "WMS_CLIENT_ID") 
  ;