CREATE TABLE "CNL_SYS"."CNL_WMS_QC_ORDER" 
   (	"QC_KEY" NUMBER(*,0), 
	"ORDER_ID" VARCHAR2(20 CHAR), 
	"CLIENT_ID" VARCHAR2(20 CHAR), 
	"SITE_ID" VARCHAR2(20 CHAR), 
	"QC_REQ_YN" VARCHAR2(1 CHAR), 
	"QC_BATCH_YN" VARCHAR2(1 CHAR), 
	"QC_QTY_DEF_YN" VARCHAR2(1 CHAR), 
	"QC_SKU_SELECT_YN" VARCHAR2(1 CHAR), 
	"QC_QTY_UPD_YN" VARCHAR2(1 CHAR), 
	"QC_SERIAL_YN" VARCHAR2(1 CHAR) DEFAULT 'N', 
	 CONSTRAINT "PK_CNL_WMS_QC_ORDER" PRIMARY KEY ("QC_KEY")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_WMS_QC_ORDER_IDX2" ON "CNL_SYS"."CNL_WMS_QC_ORDER" ("CLIENT_ID", "ORDER_ID") 
  ;