CREATE TABLE "CNL_SYS"."CNL_TMP_RUN_TASK" 
   (	"KEY" NUMBER(10,0) NOT NULL ENABLE, 
	"SITE_ID" VARCHAR2(10 CHAR), 
	"STATION_ID" VARCHAR2(256 CHAR), 
	"USER_ID" VARCHAR2(20 CHAR), 
	"STATUS" VARCHAR2(12 CHAR) NOT NULL ENABLE, 
	"COMMAND" VARCHAR2(4000 CHAR) NOT NULL ENABLE, 
	"PID" NUMBER(10,0), 
	"OLD_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"LANGUAGE" VARCHAR2(8 CHAR), 
	"NAME" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"TIME_ZONE_NAME" VARCHAR2(64 CHAR), 
	"NLS_CALENDAR" VARCHAR2(30 CHAR), 
	"PRINT_LABEL" VARCHAR2(1 CHAR), 
	"JAVA_REPORT" VARCHAR2(1 CHAR), 
	"RUN_LIGHT" VARCHAR2(1 CHAR), 
	"SERVER_INSTANCE" NUMBER(3,0), 
	"PRIORITY" NUMBER(4,0), 
	"ARCHIVE" VARCHAR2(1 CHAR), 
	"ARCHIVE_IGNORE_SCREEN" VARCHAR2(1 CHAR), 
	"ARCHIVE_RESTRICT_USER" VARCHAR2(1 CHAR), 
	"CLIENT_ID" VARCHAR2(10 CHAR), 
	"EMAIL_RECIPIENTS" VARCHAR2(4000 CHAR), 
	"EMAIL_ATTACHMENT" VARCHAR2(250 CHAR), 
	"EMAIL_SUBJECT" VARCHAR2(120 CHAR), 
	"EMAIL_MESSAGE" VARCHAR2(4000 CHAR), 
	"MASTER_KEY" NUMBER(10,0), 
	"USE_DB_TIME_ZONE" VARCHAR2(1 CHAR)
   ) ;

CREATE INDEX "CNL_SYS"."CNL_TMP_RUN_TASK_IDX" ON "CNL_SYS"."CNL_TMP_RUN_TASK" ("KEY") 
  ;