CREATE TABLE "CNL_SYS"."CNL_WHH_LOG" 
   (	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"SITE_ID" VARCHAR2(30 CHAR), 
	"CLIENT_ID" VARCHAR2(30 CHAR), 
	"ORDER_ID" VARCHAR2(30 CHAR), 
	"CONTAINER_ID" VARCHAR2(30 CHAR), 
	"PALLET_ID" VARCHAR2(30 CHAR), 
	"SKU_ID" VARCHAR2(30 CHAR), 
	"PACKAGE_NAME" VARCHAR2(30 CHAR), 
	"PROCEDURE_FUNCTION" VARCHAR2(30 CHAR), 
	"EXTRA_PARAMETERS" VARCHAR2(4000 CHAR), 
	"COMMENTS" VARCHAR2(4000 CHAR)
   ) ;

CREATE INDEX "CNL_SYS"."IDX_WHH_LOG_CLIENT" ON "CNL_SYS"."CNL_WHH_LOG" ("CLIENT_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_WHH_LOG_CONTAINER" ON "CNL_SYS"."CNL_WHH_LOG" ("CONTAINER_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_WHH_LOG_DSTAMP" ON "CNL_SYS"."CNL_WHH_LOG" ("DSTAMP") 
  ;

CREATE INDEX "CNL_SYS"."IDX_WHH_LOG_ORDER" ON "CNL_SYS"."CNL_WHH_LOG" ("ORDER_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_WHH_LOG_PALLET" ON "CNL_SYS"."CNL_WHH_LOG" ("PALLET_ID") 
  ;

CREATE INDEX "CNL_SYS"."IDX_WHH_LOG_SITE" ON "CNL_SYS"."CNL_WHH_LOG" ("SITE_ID") 
  ;