CREATE TABLE "CNL_SYS"."CNL_DWS_LOG" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"WMS_PARCEL_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"DWS_UNIT_ID" VARCHAR2(20 CHAR), 
	"DWS_STATION_ID" VARCHAR2(256 CHAR), 
	"DWS_LFT_STATUS" VARCHAR2(20 CHAR), 
	"DWS_LFT_DESCRIPTION" VARCHAR2(500 CHAR), 
	"DWS_PACKAGE_TYPE" VARCHAR2(15 CHAR), 
	"DWS_WEIGHT" NUMBER(15,6), 
	"DWS_HEIGHT" NUMBER(15,6), 
	"DWS_WIDTH" NUMBER(15,6), 
	"DWS_DEPTH" NUMBER(15,6), 
	"DWS_DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"WMS_PRINT_LABEL_YN" VARCHAR2(1 CHAR), 
	"ERROR_YN" VARCHAR2(1 CHAR), 
	"ERROR_TEXT" VARCHAR2(500 CHAR), 
	"CREATED_BY" VARCHAR2(20 CHAR), 
	"CREATION_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"LAST_UPDATED_BY" VARCHAR2(20 CHAR), 
	"LAST_UPDATE_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	 CONSTRAINT "CNL_DLG_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."IDX_DLG_PARCEL_ID" ON "CNL_SYS"."CNL_DWS_LOG" ("WMS_PARCEL_ID") 
  ;