CREATE TABLE "CNL_SYS"."CNL_OHR_INSTRUCTIONS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"SITE_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"CLIENT_ID" VARCHAR2(10 CHAR) NOT NULL ENABLE, 
	"ORDER_ID" VARCHAR2(20 CHAR) NOT NULL ENABLE, 
	"INSTRUCTIONS" VARCHAR2(180 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CNL_OIN_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CNL_OIN_UK" UNIQUE ("SITE_ID", "CLIENT_ID", "ORDER_ID")
  USING INDEX  ENABLE
   ) ;