CREATE TABLE "CNL_SYS"."CNL_CONSTANTS" 
   (	"ID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(35 CHAR) NOT NULL ENABLE, 
	"DESCRIPTION" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"VALUE" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CNL_CST_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE, 
	 CONSTRAINT "CNL_CST_NAME_UK" UNIQUE ("NAME")
  USING INDEX  ENABLE
   ) ;