CREATE TABLE "CNL_SYS"."CNL_WHH_ERROR_LOG" 
   (	"ERR_LOG_KEY" NUMBER(*,0), 
	"DSTAMP" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ERROR_DATA" NCLOB, 
	"USER_ID" VARCHAR2(50 CHAR), 
	 CONSTRAINT "PK_WHH_ERROR_LOG" PRIMARY KEY ("ERR_LOG_KEY")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_WHH_ERROR_LOG_IDX" ON "CNL_SYS"."CNL_WHH_ERROR_LOG" ("DSTAMP") 
  ;

CREATE INDEX "CNL_SYS"."CNL_WHH_ERROR_LOG_U_IDX" ON "CNL_SYS"."CNL_WHH_ERROR_LOG" ("USER_ID") 
  ;