CREATE TABLE "CNL_SYS"."CNL_AS_PICK_TASK" 
   (	"WMS_MT_KEY" NUMBER, 
	"CLIENT_ID" VARCHAR2(20), 
	"TASK_ID" VARCHAR2(20), 
	"QTY_TO_MOVE" NUMBER, 
	"CUBING_REQ" VARCHAR2(1), 
	"CATEGORY" VARCHAR2(10), 
	"CNL_IF_STATUS" VARCHAR2(20), 
	"CUBED_CONTAINER_TYPE" VARCHAR2(30), 
	"CUBED_CONTAINER_ID" VARCHAR2(30), 
	"PICKED_CONTAINER_TYPE" VARCHAR2(30), 
	"PICKED_CONTAINER_ID" VARCHAR2(30), 
	"CREATION_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"CUBED_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"PICKED_DATE" TIMESTAMP (6) WITH LOCAL TIME ZONE, 
	"ORD_MASTER_HOST_MESSAGE_KEY" NUMBER, 
	"CUB_RESULT_HOST_MESSAGE_KEY" NUMBER, 
	"PICKED_HOST_MESSAGE_KEY" NUMBER, 
	"SPLIT_PICK_KEY" NUMBER, 
	"USER_ID" VARCHAR2(20), 
	"STATION_ID" VARCHAR2(20), 
	"CONSOL_LINK" NUMBER, 
	"LINE_ID" NUMBER(6,0), 
	"DISALLOW_CUBING" VARCHAR2(1 CHAR)
   ) ;

CREATE INDEX "CNL_SYS"."CNL_AS_PICK_TASK2_IDX" ON "CNL_SYS"."CNL_AS_PICK_TASK" ("CLIENT_ID", "TASK_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_AS_PICK_TASK3_IDX" ON "CNL_SYS"."CNL_AS_PICK_TASK" ("CLIENT_ID", "TASK_ID", "CNL_IF_STATUS") 
  ;

CREATE INDEX "CNL_SYS"."CNL_AS_PICK_TASK_IDX" ON "CNL_SYS"."CNL_AS_PICK_TASK" ("WMS_MT_KEY") 
  ;

CREATE INDEX "CNL_SYS"."CNL_AS_PICK_TASK_STAT_IDX" ON "CNL_SYS"."CNL_AS_PICK_TASK" ("CNL_IF_STATUS") 
  ;