CREATE TABLE "CNL_SYS"."CNL_WMS_SORT_ORDER" 
   (	"KEY" NUMBER, 
	"LOCATION_ID" VARCHAR2(20 CHAR), 
	"ORDER_ID" VARCHAR2(20 CHAR), 
	"ORDER_COMPLETE" VARCHAR2(1 CHAR), 
	"CLIENT_ID" VARCHAR2(30 CHAR), 
	"CONTAINER_ID" VARCHAR2(30 CHAR), 
	"PRIORITY" NUMBER(4,0), 
	"EXPORT" VARCHAR2(1 CHAR), 
	 CONSTRAINT "PM_KEY" PRIMARY KEY ("KEY")
  USING INDEX  ENABLE
   ) ;

CREATE INDEX "CNL_SYS"."CNL_WMS_SORT_ORDER_IDX2" ON "CNL_SYS"."CNL_WMS_SORT_ORDER" ("ORDER_ID") 
  ;

CREATE INDEX "CNL_SYS"."CNL_WMS_SORT_ORDER_IDX3" ON "CNL_SYS"."CNL_WMS_SORT_ORDER" ("ORDER_COMPLETE") 
  ;