CREATE TABLE "CNL_SYS"."CNL_FILES_ARCHIVE" 
   (	"ID" NUMBER(20,0) NOT NULL ENABLE, 
	"APPLICATION" VARCHAR2(50 CHAR) NOT NULL ENABLE, 
	"LOCATION" VARCHAR2(100 CHAR) NOT NULL ENABLE, 
	"FILENAME" VARCHAR2(1000 CHAR) NOT NULL ENABLE, 
	"STATUS" VARCHAR2(20 CHAR) DEFAULT 'Created' NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"CREATION_DATE" DATE NOT NULL ENABLE, 
	"LAST_UPDATED_BY" VARCHAR2(30 CHAR) NOT NULL ENABLE, 
	"LAST_UPDATE_DATE" DATE NOT NULL ENABLE, 
	 CONSTRAINT "CNL_FAE_PK" PRIMARY KEY ("ID")
  USING INDEX  ENABLE
   ) ;