CREATE TABLE "CNL_SYS"."MLOG$_CNL_ACTIVE_CLIENTS" 
   (	"DB_LINK" VARCHAR2(7 CHAR), 
	"SITE_ID" VARCHAR2(10 CHAR), 
	"CLIENT_ID" VARCHAR2(10 CHAR), 
	"SNAPTIME$$" DATE, 
	"DMLTYPE$$" VARCHAR2(1 CHAR), 
	"OLD_NEW$$" VARCHAR2(1 CHAR), 
	"CHANGE_VECTOR$$" RAW(255), 
	"XID$$" NUMBER
   ) ;

CREATE INDEX "CNL_SYS"."I_MLOG$_CNL_ACTIVE_CLIENTS" ON "CNL_SYS"."MLOG$_CNL_ACTIVE_CLIENTS" ("XID$$") 
  ;