CREATE GLOBAL TEMPORARY TABLE "CNL_SYS"."RUPD$_CNL_ACTIVE_CLIENTS" 
   (	"DB_LINK" VARCHAR2(7 CHAR), 
	"SITE_ID" VARCHAR2(10 CHAR), 
	"CLIENT_ID" VARCHAR2(10 CHAR), 
	"DMLTYPE$$" VARCHAR2(1 CHAR), 
	"SNAPID" NUMBER(*,0), 
	"CHANGE_VECTOR$$" RAW(255)
   ) ON COMMIT PRESERVE ROWS ;