CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_PRODUCT_ATTRIBUTE" ("CLIENT_ID", "SKU_ID", "PRODUCT_ATTRIBUTE_KEY", "ATTRIBUTE_ID", "CHECK_IN_BEHAVIOR", "DEFAULT_VALUE", "PICKING_BEHAVIOR", "PUT_AWAY_BEHAVIOR", "PRODUCT_KEY") AS 
  select P.OWNER_ID AS CLIENT_ID,P.PRODUCT_ID as SKU_ID, A.PRODUCT_ATTRIBUTE_KEY,A.ATTRIBUTE_ID,A.CHECK_IN_BEHAVIOR,A.DEFAULT_VALUE,A.PICKING_BEHAVIOR,A.PUT_AWAY_BEHAVIOR,A.PRODUCT_KEY
from    rhenus_synq.host_product_attribute@as_synq A
,       rhenus_synq.host_product@as_synq P
where   A.PRODUCT_KEY = P.PRODUCT_KEY
order by product_attribute_key desc