CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_ATTRIBUTE" ("ATTRIBUTE_VALUE_KEY", "CLASS_TYPE", "ATTRIBUTE_NAME", "ATTRIBUTE_VALUE", "ATTRIBUTE_ROLE", "LU_KEY", "ASN_LINE_KEY", "ORDER_LINE_KEY") AS 
  select  ATTRIBUTE_VALUE_KEY,CLASS_TYPE,ATTRIBUTE_NAME,ATTRIBUTE_VALUE,ATTRIBUTE_ROLE,LU_KEY,ASN_LINE_KEY,ORDER_LINE_KEY
from    rhenus_synq.host_attribute@as_synq
order by attribute_value_key desc