CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_ORDER_TU_PICK" ("ORDER_TU_PICK_KEY", "ORDER_ID", "OWNER_ID", "SHIPMENT_ID", "STOP_SEQUENCE", "USER_ID", "WORKSTATION_ID") AS 
  select  ORDER_TU_PICK_KEY,ORDER_ID,OWNER_ID,SHIPMENT_ID,STOP_SEQUENCE,USER_ID,WORKSTATION_ID
from    rhenus_synq.host_order_tu_pick@as_synq
order by order_tu_pick_key desc