CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_PRODUCT_UOM" ("CLIENT_ID", "SKU_ID", "PRODUCT_UOM_KEY", "BASE_UOM", "PICK_UOM", "PRODUCT_UOM_TREE", "PUTAWAY_UOM", "RATIO", "UOM_ID", "WEIGHT_TOLERANCE", "HEIGHT", "LENGTH", "VOLUME", "WEIGHT", "WIDTH", "PRODUCT_KEY") AS 
  select  P.OWNER_ID AS CLIENT_ID, P.PRODUCT_ID AS SKU_ID, U.PRODUCT_UOM_KEY,U.BASE_UOM,U.PICK_UOM,U.PRODUCT_UOM_TREE,U.PUTAWAY_UOM,U.RATIO,U.UOM_ID,U.WEIGHT_TOLERANCE,U.HEIGHT,U.LENGTH,U.VOLUME,U.WEIGHT,U.WIDTH,U.PRODUCT_KEY
from    rhenus_synq.host_product_uom@as_synq u
,       rhenus_synq.host_product@as_synq P
WHERE   P.PRODUCT_KEY = U.PRODUCT_KEY
order by product_uom_key desc