CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_ORDER_TU" ("ORDER_TU_KEY", "CATEGORY", "ORDER_ID", "OWNER_ID", "TU_ID", "TU_TYPE", "CUBING_RESULT_KEY", "TU_EXPECTED_WEIGHT", "LAST_BOX") AS 
  select  ORDER_TU_KEY,CATEGORY,ORDER_ID,OWNER_ID,TU_ID,TU_TYPE,CUBING_RESULT_KEY,TU_EXPECTED_WEIGHT,LAST_TU_FOR_ORDER
from    rhenus_synq.host_order_tu@as_synq
order by order_tu_key desc