CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_ORDER_STATUS_CHANGE" ("ORDER_STATUS_CHANGE_KEY", "ORDER_ID", "OWNER_ID", "PREVIOUS_STATE", "STATE", "WORKSTATION") AS 
  select  ORDER_STATUS_CHANGE_KEY,ORDER_ID,OWNER_ID,PREVIOUS_STATE,STATE,WORKSTATION
from    rhenus_synq.host_order_status_change@as_synq
order by order_status_change_key desc