CREATE OR REPLACE FORCE VIEW "CNL_SYS"."AS_HOST_ORDER_HEADER" ("ORDER_KEY", "AUTO_ALLOC_ALLOWED", "CAPABILITY", "DISPATCH_DATE", "MULTIPLE_VAS_ALLOWED", "ORDER_DATE", "ORDER_ID", "ORDER_TYPE", "OWNER_ID", "PRIORITY", "SHORT_ALLOCATION_ALLOWED", "SHORT_RELEASING_ALLOWED", "SHORT_SHIPPING_ALLOWED") AS 
  select  ORDER_KEY,AUTO_ALLOC_ALLOWED,CAPABILITY,DISPATCH_DATE,MULTIPLE_VAS_ALLOWED,ORDER_DATE,ORDER_ID,ORDER_TYPE,OWNER_ID,PRIORITY,SHORT_ALLOCATION_ALLOWED,SHORT_RELEASING_ALLOWED,SHORT_SHIPPING_ALLOWED
from    rhenus_synq.host_order_header@as_synq
order by order_key desc